### ISSUE TITLE
复现请教

### ISSUE THREAD

**Issue by Andy-HuY** [JIANGYUE61610306/SAGDFN#2]
您好，在复现过程中碰到以下问题（使用的是carpark数据），还请您赐教，十分感谢！

root@autodl-container-dd024aa9fd-08e615af:~/autodl-tmp/SAGDFN-main# /root/miniconda3/bin/python /root/autodl-tmp/SAGDFN-main/train.py
2024-07-01 15:44:59.193792: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-01 15:44:59.236697: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 AVX_VNNI AMX_TILE AMX_INT8 AMX_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-01 15:44:59.918004: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
2024-07-01 15:45:00,810 - INFO - Log directory: data/model/SAGDFN_DR_3_h_12_64_lr_0.001_bs_64_0701154500/
torch.Size([1918, 200])
2024-07-01 15:45:58,955 - INFO - Model created with threshold: 0.8
2024-07-01 15:45:58,976 - INFO - Start training ...
2024-07-01 15:45:58,976 - INFO - num_batches:192
Num of epoch: 0
2024-07-01 15:45:59,553 - INFO - Total trainable parameters 222834
Traceback (most recent call last):
  File "/root/autodl-tmp/SAGDFN-main/train.py", line 23, in <module>
    main(args)
  File "/root/autodl-tmp/SAGDFN-main/train.py", line 15, in main
    supervisor.train()
  File "/root/autodl-tmp/SAGDFN-main/model/pytorch/supervisor.py", line 155, in train
    return self._train(**kwargs)
  File "/root/autodl-tmp/SAGDFN-main/model/pytorch/supervisor.py", line 405, in _train
    output, mid_output, adj_save = self.SAGDFN_model(x, self._train_feas, y, batches_seen, batch_idx)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/autodl-tmp/SAGDFN-main/model/pytorch/model.py", line 304, in forward
    self.node_index = self.filter_neigb(x, self.node_index, self.sub)
  File "/root/autodl-tmp/SAGDFN-main/model/pytorch/model.py", line 247, in filter_neigb
    senders.append(x[node_index[t,:],:])
IndexError: too many indices for tensor of dimension 1

发现第一次循环的时候node_index是（num_nodes, 100）,第二次循环的时候就变成了（100）

**Comment by luoyi-hi** [comment]
您好，我也遇到了此问题，我是将其改成：“self.node_index2 = self.filter_neigb(x, self.node_index, self.sub)”，并将后续的self.node_index改成self.node_index2，以保证后续循环维度不会发生改变，请问您有其他解决办法吗
